# Domino Postgres resource
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
        - name: {{ .Release.Name }}-postgres
          image: {{ .Values.database.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.name }}
            - name: POSTGRES_USER
              value: {{ .Values.database.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.password }}
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "pgdata"
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
      volumes:
        - hostPath:
            path: "/home/docker/pgdata"
          name: pgdata

---
# Domino Postgres Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-postgres
  ports:
    - protocol: "TCP"
      port: 5432
      targetPort: 5432
