apiVersion: v2
name: domino
description: A Helm chart for Domino
type: application
version: 0.1.0
appVersion: 0.1.0
home: https://github.com/Tauffer-Consulting/domino
sources:
  - https://github.com/Tauffer-Consulting/domino
dependencies:
  - name: airflow
    version: 1.9.0
    repository: https://airflow.apache.org/
